import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "react-hot-toast";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "ShopMart",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* Navbar */}
          <Navbar />
          {/* Main App */}
          <div className="container mx-auto pt-30 min-h-screen flex items-center">
            <Toaster />
            {children}
          </div>
          {/* Footer */}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
